name: go version

on:
  workflow_dispatch:
    inputs:
      version:
        description: Select version  
        default: 1.19.1

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone 
        uses: actions/checkout@v3
      
      - name: Set up go      
        uses: actions/setup-go@v3
        with:
          go-version: ${{inputs.version}}
        
      - name: Run Hello world
        run: go run hello.go
      
      - name: Run test file
        run: go run main_test.go
